<?php namespace Ext; 

class Worker implements WorkerService {

	/**
	* Can serve all services of WorerService
	*
	* @param bool Always TRUE
	*/
	static public function canServe($mixed) { return TRUE; }

	/**
	* Find path of the extension I am currently in!
	* 
	* If I am in a subdirectory of the extension I get the extension path.
	* If I am outside I get FALSE,
	*
	* @param string For recursion only. Don't set it.
	* @param mixed  FALSE or the extension path.
	*/
	public function findPathOfCurrentExtension($currentDir = NULL) {
		$currentDir = $currentDir ? $currentDir : getcwd();
		if(file_exists($currentDir.'/ext_emconf.php')) {
			return $currentDir;
		} else {
			$childDir = dirname($currentDir);
			// walk up 
			if($childDir != $currentDir) 
				return $this->findPathOfCurrentExtension($childDir);
			// at root dir
			else 
				return FALSE;
		}
	}

	/**
	* Return basename as extension key
	*
	* @param string Path to extesnion.
	* @return string Key of extension.
	*/
	public function getKeyFromExtensionPath($extensionPath) {
		return basename(realpath($extensionPath));
	}

	public function readEmConf($extensionPath) {
		$_EXTKEY = 'Dummy';
		include($extensionPath.'/ext_emconf.php');
		return $EM_CONF['Dummy'];
	}
	
	/**
	* Write given data array to to ext_emconf.php
	*
	* Replaces the old version.
	*
	* @param string extension directory
	* @param string extension key
	* @param array  emConf data
	* @return void
	*
	* @author Tobias Liebig 
	* @author Elmar Hinz
	*/
	public function writeEmConf($extensionPath, $extKey, $data) {
		date_default_timezone_set('UTC');
		$code = var_export($data, TRUE);
		$code = str_replace(' ', "\t", $code);
		$code = '<?php

/***************************************************************
* Extension Manager/Repository config file for ext "'.$extKey.'".
*
* Generated by ext ' . date('d-m-Y H:i') . '
*
* https://github.com/t3elmar/Ext
***************************************************************/

$EM_CONF[$_EXTKEY] = ' . var_export($data, TRUE) . ';

?>';

		$fileHandler = fopen($extensionPath . '/ext_emconf.php', 'wb');
		fwrite($fileHandler, $code);
		fclose($fileHandler);
	}

} 

?>

